# Generated by Django 4.1.7 on 2023-07-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=100)),
                ('Address', models.TextField(max_length=800)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
    ]
